### ISSUE TITLE
Experiment on Cora

### ISSUE THREAD

**Issue by jujulili888** [devnkong/FLAG#11]
Hi, 
Sorry to bother you, I am wondering if there is any experiment using GCN on Cora dataset in your code? I am still not finding that yet.

**Comment by devnkong** [comment]
Hi, 

Sorry for the late reply! Do you still need that code?

**Comment by jujulili888** [comment]
Thanks for your reply! I've already solved my problems now. Just forgetting about my requirement is OK.😊

**Comment by devnkong** [comment]
Thank you! Hope experiments go smoothly.
