### ISSUE TITLE
Add perturb before or after node encoder?

### ISSUE THREAD

**Issue by QJ-Chen** [devnkong/FLAG#12]
To my understanding, for the graphprop tasks, the perturb is add to the input node embedding, output of the node encoder while in the nodeprop tasks, the perturb is added directly to the node feature. Have you test the difference?

```python
# graphprop
def forward(self, batched_data, perturb=None):
    x, edge_index, edge_attr, batch = batched_data.x, batched_data.edge_index, batched_data.edge_attr, batched_data.batch

    ### computing input node embedding
    tmp = self.atom_encoder(x) + perturb if perturb is not None else self.atom_encoder(x)
```
```python
# nodeprop
def train_flag(model, x, y_true, train_idx, optimizer, args, device) :

    forward = lambda perturb : model(x[train_idx] + perturb)
    model_forward = (model, forward)
    y = y_true.squeeze(1)[train_idx]
    loss, _ = flag(model_forward, x[train_idx].shape, y, args, optimizer, device, F.nll_loss)
    return loss.item()

```

**Comment by devnkong** [comment]
Hi, thanks for your interest in our work. The reason we add perturbation on the output of node encoder in the graph classification task is to achieve the goal of doing data augmentation in continuous feature space. The raw input node features in the graph task are categorical features. It will be suboptimal to add continuous perturbation on that. While on the node task the features are already preprocessed and projected into continuous space so we can directly add perturbation on that.

**Comment by QJ-Chen** [comment]
I'm considering the scale of node encoder output. As the encoder is updated during training, the feature scale changes while the step size of flag is fixed. This might damage the robustness I think.  

I'm interesting in the graph augmentation field and repeat your work recently. Looking forward to discussing more with you.

**Comment by devnkong** [comment]
This is an interesting idea. The reason we did not perform such fine-grained investigation on the augmentation technique is that we want to make our method widely applicable to various tasks and datasets. And yes I believe there is definitely room for improvement. Hope things work out for you!
