### ISSUE TITLE
no code for DeepGCN+FLAG on ogbg-molpcba and ogbg-code

### ISSUE THREAD

**Issue by lipingcoding** [devnkong/FLAG#2]
no code for DeepGCN+FLAG on ogbg-molpcba and ogbg-code

**Comment by devnkong** [comment]
The code for DeeperGCN+FLAG for ogbg-molpcba is right here https://github.com/devnkong/FLAG/tree/main/deep_gcns_torch/examples/ogb/ogbg_mol

The DeeperGCN baselines didn't include ogbg-code implementations and results, so we don't have the code here. 
You could see the original DeeperGCN experiments here
https://github.com/lightaime/deep_gcns_torch/tree/master/examples/ogb

**Comment by lipingcoding** [comment]
thanks for your reply!
