### ISSUE TITLE
what is flag_product?

### ISSUE THREAD

**Issue by ShunliRen** [devnkong/FLAG#4]
when i run the code ogbn-product/gat/gat_ns.py, i didn't find where the 'flag_product' function be defined. So i would like to know what the function mean and where i can find it.

**Comment by devnkong** [comment]
Hello, the `flag_products` function is defined at https://github.com/devnkong/FLAG/blob/c19ae31ff80a41fe4fa0c011cc1e38b83511df45/ogb/attacks.py#L66-L105.

The function is to carry out the forward and backward computation for GNNs using FLAG.

**Comment by ShunliRen** [comment]
> Hello, the `flag_products` function is defined at
> 
> https://github.com/devnkong/FLAG/blob/c19ae31ff80a41fe4fa0c011cc1e38b83511df45/ogb/attacks.py#L66-L105
> 
> .
> The function is to carry out the forward and backward computation for GNNs using FLAG.

thank you very much!  I have found it.
